version: "3.7"
services:
    app:
        build:
            args:
                user: app
                uid: 1000
            context: ./
            dockerfile: dockerfile
        image: sms_gateway_back_end
        container_name: sms_gateway_back_end
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            -   db
        networks:
            - sms_gateway

    db:
        image: mysql:5.7
        container_name: sms_gateway_database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - sms_gateway
    nginx:
        image: nginx:1.17-alpine
        container_name: sms_gateway_web_server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - sms_gateway



networks:
    sms_gateway:
        driver: bridge
