<?php

namespace MODULES\SMS\Tests\Unit\Ghasedak;



use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\Psr7\Response;
use MODULES\SMS\Drivers\Ghasedak\Ghasedak;
use PHPUnit\Framework\TestCase;

class GhasedakDriverTest extends TestCase
{
    public $ghasedak;
    public $mock;
    public function setUp(): void
    {
        $this->mock=new MockHandler();
        $this->ghasedak=new Ghasedak("test","http://localhost/v1/",false);
        $this->ghasedak->setHttpClient(new Client(['handler'=>$this->mock]));
        parent::setUp();
    }

    public function test_send_sms(){
        $this->mock->append(new Response(200, [], file_get_contents(__DIR__.'/mockResponse/send.json')));
        $response=$this->ghasedak->send("09101234556","this is a text message");
        $this->assertEquals(200,$response->getStatusCode());
    }
    public function tearDown(): void
    {
        $this->mock->reset();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
